import Head from "next/head";

export default function Fail() {
  return (
    <>
      <Head>
        <title>Fail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Fail</h1>
        <p>Survey submission failed</p>
      </main>
    </>
  );
}
