version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: godfist123/backend:latest

    ports:
      - "3005:3005"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production

  frontend-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: godfist123/frontend-client:latest

    ports:
      - "3000:3000"
    volumes:
      - ./survey_client:/usr/src/app
      - /usr/src/app/node_modules

  frontend-business:
    build:
      context: .
      dockerfile: Dockerfile.business
    image: godfist123/frontend-business:latest
    ports:
      - "8000:80"
    volumes:
      - ./survey_business:/usr/src/app
      - /usr/src/app/node_modules
