name: CI - Build and Push Docker Images

on:
  push:
    branches:
      - main # Trigger CI pipeline when code is pushed to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Images using Docker Compose
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Images using Docker Compose
      - name: Build and Push Images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
